### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/iris-flow#1]
$ iris session iris "##class(%ZPM.PackageManager).Shell(\"test iris-flow -v\",1,1)"

[iris-flow]     Reload START (/home/irisowner/irisbuild/)
chmod -R 775 /usr/irissys/csp/iris-flow/
[iris-flow]     Reload FAILURE
ERROR! Error copying directory /home/irisowner/irisbuild/src/csp/ to /usr/irissys/csp//iris-flow/
  > ERROR #5021: Directory '/home/irisowner/irisbuild/src/csp/' does not exist.$

**Comment by rcemper** [comment]
PR for fix is provided

**Comment by jrpereirajr** [comment]
Merged! Thank you Robert!
